# Generated by Django 4.1.1 on 2022-09-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.CharField(blank=True, max_length=255, verbose_name="著者"),
        ),
    ]
