# Generated by Django 4.1.1 on 2022-09-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbr", "0002_book_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="画像"
            ),
        ),
    ]
