# Generated by Django 4.1.1 on 2022-09-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbr", "0003_book_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/", verbose_name="画像"
            ),
        ),
    ]
