# Generated by Django 4.1.1 on 2022-09-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbr", "0004_alter_book_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="impression",
            name="point",
            field=models.DecimalField(
                decimal_places=1, default=0, max_digits=1, verbose_name="点数"
            ),
        ),
    ]
