# Generated by Django 4.1.1 on 2022-09-24 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rbr", "0005_impression_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="impression",
            name="point",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="点数",
            ),
        ),
    ]
